### PR TITLE
Release RockLib.Diagnostics.2.0.1

### PR DESCRIPTION
**Pull request by chrisferrantelli**
## Description
Releasing updated RockLib.Diagnostics package for the bugfix

## Type of change:  2

1. Non-functional change (e.g. documentation changes, removing unused `using` directives, renaming local variables, etc)
2. Bug fix (non-breaking change that fixes an issue)
3. New feature (non-breaking change that adds functionality)
4. Breaking change (fix or feature that could cause existing functionality to not work as expected)

## Checklist:

- Have you reviewed your own code? Do you understand every change?
- Are you following the [contributing guidelines](../blob/main/CONTRIBUTING.md)?
- Have you added tests that prove your fix is effective or that this feature works?
- New and existing unit tests pass locally with these changes?
- Have you made corresponding changes to the documentation?
- Will this change require an update to an example project? (if so, create an issue and link to it)

---

<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>

### CODE REVIEW

**Comment by NeilSchiefer** [comment]
Just have to bump the dependency to 2.0.1 further down in the csproj.

**Comment by chrisferrantelli** [comment]
My bad. Realized I couldn't push after cloning it from the main repo so forked it instead and forgot to edit that part. All fixed now.

**Review by NeilSchiefer — APPROVED** [review]

**Comment by kristycurrier** [comment]
I would update the description to what package, its version and a link to the changelog of what the fix is.

**Review by kristycurrier — CHANGES_REQUESTED** [review]
Please update to the latest version of RockLib.Configuration.ObjectFactory.

**Comment by NeilSchiefer** [comment]
> Please update to the latest version of RockLib.Configuration.ObjectFactory.

I thought you said to only update to 2.0.1?:)

**Comment by kristycurrier** [comment]
> > Please update to the latest version of RockLib.Configuration.ObjectFactory.
> 
> I thought you said to only update to 2.0.1?:)

Oh... only update this package to 2.0.1. Basically we do not update the bug numbers together. So the other package being 2.0.2 does not mean this package is 2.0.2.

**Comment by NeilSchiefer** [comment]
> > > Please update to the latest version of RockLib.Configuration.ObjectFactory.
> > 
> > 
> > I thought you said to only update to 2.0.1?:)
> 
> Oh... only update this package to 2.0.1. Basically we do not update the bug numbers together. So the other package being 2.0.2 does not mean this package is 2.0.2.

Oh yeah that makes sense.  I misunderstood earlier.

**Comment by chrisferrantelli** [comment]
@kristycurrier yeah I misunderstood earlier as well, but makes sense. And realized this doesn't use CircleCI to auto deploy the package. I'll do that now.

**Review by NeilSchiefer — APPROVED** [review]

**Review by kristycurrier — APPROVED** [review]

**Pull request merged**
